app: web-scraping-node-api
service: web-scraping-node-api
frameworkVersion: "3"

custom:
  tableName: "bestsellers-table-${sls:stage}"
  esbuild:
    bundle: true
    minify: false

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [BestsellersTable, Arn]
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.tableName}

functions:
  api:
    handler: dist/server.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    BestsellersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}